"""Generate README.pypi.md — the PyPI long description — from README.md.

README.md is the only readme maintained in git, and its image/link targets are
repo-relative so GitHub renders them against the repository. PyPI cannot: it
renders the description baked into the wheel/sdist metadata at build time,
with no repository to resolve against. This script bridges the two by
rewriting every relative target to an absolute, version-tagged GitHub URL:

    ![...](doc/images/x.jpg)
        -> https://raw.githubusercontent.com/crftwr/keyhac/v2.0.0/doc/images/x.jpg
    [...](doc/installation.md)
        -> https://github.com/crftwr/keyhac/blob/v2.0.0/doc/installation.md

Tag URLs, not ``main``, so the PyPI page for a release keeps showing that
release's images forever, however far ``main`` moves on. `make tag` bumps the
version, runs `make build` as a gate, then pushes the ``vX.Y.Z`` tag before
`make release-whl` uploads — so the URLs resolve by the time the PyPI page
updates. Between releases the rewrite targets the *previous* tag — a
screenshot added mid-cycle reaches PyPI at the next release, which is
inherent to tagged URLs.

The output is regenerated by `make build` on every run and is gitignored —
never commit it; it embeds one release's version. pyproject.toml points its
dynamic ``readme`` at it. When the file is absent — a fresh clone running
``pip install -e .`` directly — setuptools tolerates the missing file and the
local metadata simply carries an empty description, which nothing reads; the
`twine check --strict` in `make build` is what keeps an empty description
from ever reaching an upload.

Absolute URLs and intra-page ``#anchors`` pass through untouched.

Same scheme as PuiKit's scripts/gen_pypi_readme.py.
"""

import re

from _version_source import REPO_ROOT, read_version

SOURCE = REPO_ROOT / "README.md"
OUTPUT = REPO_ROOT / "README.pypi.md"

BLOB_BASE = "https://github.com/crftwr/keyhac/blob"
RAW_BASE = "https://raw.githubusercontent.com/crftwr/keyhac"

#: A markdown image (``![alt](target)``) or link (``[text](target)``).
#: Targets containing whitespace or a "title" part aren't matched — README.md
#: has none, and an unmatched link is left alone rather than mangled.
LINK = re.compile(r"(!?)\[([^\]]*)\]\(([^)\s]+)\)")

#: An absolute target: a URI scheme (https:, mailto:, ...) per RFC 3986.
SCHEME = re.compile(r"[A-Za-z][A-Za-z0-9+.-]*:")


def rewrite(text: str, version: str) -> tuple[str, int]:
    """Return README text with relative targets absolutized, and the count."""
    count = 0

    def repl(m: re.Match) -> str:
        nonlocal count
        bang, label, target = m.groups()
        if SCHEME.match(target) or target.startswith("#"):
            return m.group(0)
        path = target.removeprefix("./")
        # Images need the raw file (github.com/blob serves an HTML page);
        # everything else wants the browsable blob page.
        base = RAW_BASE if bang else BLOB_BASE
        count += 1
        return f"{bang}[{label}]({base}/v{version}/{path})"

    return LINK.sub(repl, text), count


def main() -> int:
    version = read_version()
    text, count = rewrite(SOURCE.read_text(encoding="utf-8"), version)
    header = (
        f"<!-- Generated from README.md by tools/gen_pypi_readme.py; relative\n"
        f"     links rewritten against the v{version} tag for PyPI. Do not edit\n"
        f"     or commit. -->\n\n"
    )
    OUTPUT.write_text(header + text, encoding="utf-8")
    print(f"{OUTPUT.name}: {count} relative link(s) -> v{version} URLs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
